"use client";

import { useMemo, useState } from "react";
import { MacroGenerationResult, MacroSpecification } from "@/lib/types";
import { safeBasFilename } from "@/lib/filename";
import { SAFETY_DISCLAIMER, scanVbaForWarnings } from "@/lib/safetyScanner";

function downloadTextFile(filename: string, contents: string) {
  const blob = new Blob([contents], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function ResultPanel({
  result,
  specification,
  macroName,
  onStartOver,
}: {
  result: MacroGenerationResult;
  specification: MacroSpecification;
  macroName: string;
  onStartOver: () => void;
}) {
  const [code, setCode] = useState(result.vbaCode);
  const [copyStatus, setCopyStatus] = useState<string | null>(null);

  const warnings = useMemo(() => scanVbaForWarnings(code), [code]);

  const filename = safeBasFilename(macroName || specification.macroName);

  async function handleCopyVba() {
    const ok = await copyToClipboard(code);
    setCopyStatus(ok ? "VBA copied to clipboard." : "Could not copy — select and copy manually.");
  }

  async function handleCopySpec() {
    const ok = await copyToClipboard(JSON.stringify(specification, null, 2));
    setCopyStatus(ok ? "Specification copied to clipboard." : "Could not copy — select and copy manually.");
  }

  function handleDownloadBas() {
    downloadTextFile(filename, code);
  }

  return (
    <div className="card">
      <h2 className="card-title">Generated macro</h2>
      <p className="card-subtitle">
        Nothing here has been run. Review every line, then copy it into the VBA editor yourself.
      </p>

      <div className="callout callout--red" role="alert">
        <span className="callout-title">Review before running</span>
        This code was generated by an AI model from your specification. It can be wrong, incomplete, or destructive
        even if it looks plausible. Always test on a copy of your workbook first — never claim, and never assume,
        that this code is verified safe.
      </div>

      <h3 className="section-heading">Summary</h3>
      <p>{result.summary || "No summary was provided."}</p>

      <h3 className="section-heading">VBA code (editable)</h3>
      <label className="field-hint" htmlFor="vba-code-area">
        Edit freely before copying or downloading — your edits are preserved.
      </label>
      <textarea
        id="vba-code-area"
        className="code-area"
        value={code}
        onChange={(e) => setCode(e.target.value)}
        spellCheck={false}
        aria-label="Generated VBA code, editable"
      />

      <div className="btn-row">
        <button type="button" className="btn btn--primary" onClick={handleCopyVba}>
          Copy VBA
        </button>
        <button type="button" className="btn" onClick={handleDownloadBas}>
          Download {filename}
        </button>
        <button type="button" className="btn" onClick={handleCopySpec}>
          Copy specification
        </button>
        <button type="button" className="btn btn--danger-outline" onClick={onStartOver}>
          Start over
        </button>
      </div>
      {copyStatus && (
        <p role="status" className="field-hint" style={{ marginTop: 8 }}>
          {copyStatus}
        </p>
      )}

      <h3 className="section-heading">Static safety scan</h3>
      <p className="field-hint">{SAFETY_DISCLAIMER}</p>
      {warnings.length === 0 ? (
        <p className="callout" style={{ marginTop: 8 }}>
          No known destructive/external patterns were matched in the current code. This is not proof the code is
          safe — read it yourself.
        </p>
      ) : (
        <ul className="list-plain" aria-label="Safety scan warnings">
          {warnings.map((w, i) => (
            <li key={`${w.category}-${i}`}>
              <span className="badge badge--amber">{w.category}</span> {w.message}{" "}
              <code>{w.matchedText}</code>
            </li>
          ))}
        </ul>
      )}

      <h3 className="section-heading">Assumptions made</h3>
      {result.assumptions.length > 0 ? (
        <ul className="list-plain">
          {result.assumptions.map((a, i) => (
            <li key={i}>{a}</li>
          ))}
        </ul>
      ) : (
        <p className="field-hint">None reported.</p>
      )}

      <h3 className="section-heading">Open questions / missing details</h3>
      {result.openQuestions.length > 0 ? (
        <ul className="list-plain">
          {result.openQuestions.map((q, i) => (
            <li key={i}>{q}</li>
          ))}
        </ul>
      ) : (
        <p className="field-hint">None reported.</p>
      )}

      <h3 className="section-heading">Expected inputs/outputs</h3>
      <p>{result.inputsOutputs || "Not provided."}</p>

      <h3 className="section-heading">Installation / run instructions</h3>
      <p style={{ whiteSpace: "pre-wrap" }}>{result.installInstructions || "Not provided."}</p>

      <h3 className="section-heading">Test plan (use a copy of the workbook)</h3>
      {result.testPlan.length > 0 ? (
        <ol className="list-plain">
          {result.testPlan.map((t, i) => (
            <li key={i}>{t}</li>
          ))}
        </ol>
      ) : (
        <p className="field-hint">None reported.</p>
      )}

      <h3 className="section-heading">Safety cautions</h3>
      {result.safetyCautions.length > 0 ? (
        <ul className="list-plain">
          {result.safetyCautions.map((c, i) => (
            <li key={i}>{c}</li>
          ))}
        </ul>
      ) : (
        <p className="field-hint">None reported.</p>
      )}

      <h3 className="section-heading">Platform limitations</h3>
      {result.platformLimitations.length > 0 ? (
        <ul className="list-plain">
          {result.platformLimitations.map((p, i) => (
            <li key={i}>{p}</li>
          ))}
        </ul>
      ) : (
        <p className="field-hint">None reported.</p>
      )}
    </div>
  );
}
